id: P50AB4A35
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: es
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    e85b9fef33ff490b969562b562bcaa9a:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    45bb3b25f99c4b41aee590cb94509271:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    c69a79f05dd24bc689352b3ff3c32ac7:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    3962edd8d8be495793c51f6a7b437c3f:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    9aa3247a4349463180987ff295caec97:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    2dbac9b1f9204f878dc68019e7601fe3:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    cabcc6d3891241a0a9b84167c4698e05:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    93dd4fdfd3564374bccff219ac05c242:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    4decd408ed4840cb8c144c49b724fe3d:
      title: Prayer to Gesar
      parent: Prayers
    c9d6929e7e704fc1a66b579cd942d020:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    55cbd98ff71e49f18a2e075965da6847:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    8e139fa04c2041a1acd648a819ebfab5:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    89e44894ee3a414da829bca1028a4f3d:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.453454'
last_modified_at: '2022-03-01T03:43:17.453457'
